name: proteus

services:
    ner-gcc-arm:
        image: ghcr.io/northeastern-electric-racing/embedded-base:main
        build: .
        #network_mode: host
        privileged: true
        volumes:
            - type: bind
              source: .
              target: /home/app
        tty: true
        #expose:
        #    - "3240"
        environment:
            - DEBUG_PORT=/dev/ttyUSB0
            - STM_TARGET_NAME=stm32h7
        #    - USBIP_PORT=1-1.4        
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        
